spring:
    application:
        name: effective-mobile-test

    datasource:
        url: jdbc:postgresql://localhost:{APP_PORT}/{APP_DB_NAME}
        username: {APP_USERNAME}
        password: {APP_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: none
        show-sql: true